### ISSUE TITLE
Amélioration

### ISSUE THREAD

**Issue by NATHAN76543217** [cacharle/libasm_test#1]
Hello, to make your tester much more efficients, don't just print the test's result, but the test itself too.

Have a good Day, 
Nathan

**Comment by cacharle** [comment]
Hi, by 'the test itself' do you mean the testing code or the arguments passed to the tested function?

1eb2d4832a590c809e38840f970b4506661c89cf

**Comment by NATHAN76543217** [comment]
the arguments,  cause it's hard to find which test failed in source code :)

**Comment by cacharle** [comment]
4388cc2d74f1ee8930ca1baaeeea67da925f8a2c should add more precise informations on the tested arguments except for ft_strdup because it's obvious.

I couldn't find a may to make libasm on Linux, so I haven't tested my modifications yet.
Feel free to report any compilation error/crash if you're on Mac.
